import type { Project } from './types';

/**
 * Project catalogue — the single source of truth for the Projects carousel
 * and case-study detail view. Imported by Carousel/CaseModal and used to
 * build JSON-LD structured data for SEO. Each entry's `fr` field holds the
 * French translation of its translatable copy; use `localizeProjects` to
 * resolve a list for a given locale.
 */
export const projects: Project[] = [
  {
    id: 'fitcore',
    kind: 'Personal project',
    year: '2026',
    live: null,
    name: 'Fit-Core',
    tagline: 'Cross-platform fitness & nutrition companion',
    cover: '/assets/fitcore/home.webp',
    coverPos: 'top center',
    desc: 'A full fitness app designed and built end to end — guided health-profile onboarding with BMI & calorie targeting, AI-generated workout plans, and detailed nutrition tracking for calories, macros and water. Backed by Supabase with gamified streaks, XP and badges to keep training consistent.',
    feats: [
      'AI workout generation from natural-language goals',
      'Nutrition, macro & water tracking with daily targets',
      'Gamified streaks, XP and unlockable badges',
      'Native Android build via Capacitor',
    ],
    stack: ['Angular 20', 'Ionic', 'Capacitor', 'Supabase', 'TypeScript', 'Chart.js'],
    shape: 'phone',
    gallery: [
      { src: '/assets/fitcore/home.webp', cap: 'Home dashboard' },
      { src: '/assets/fitcore/workouts.webp', cap: 'Workouts · AI generation' },
      { src: '/assets/fitcore/nutrition.webp', cap: 'Meals & water tracking' },
      { src: '/assets/fitcore/calories.webp', cap: 'Calories & macro targets' },
      { src: '/assets/fitcore/onboarding.webp', cap: 'Health-profile onboarding' },
    ],
    fr: {
      kind: 'Projet personnel',
      tagline: 'Compagnon fitness & nutrition multiplateforme',
      desc: 'Une application fitness complète conçue et développée de bout en bout — onboarding guidé avec profil santé, IMC et objectifs caloriques, plans d’entraînement générés par IA, et suivi nutritionnel détaillé (calories, macros, eau). Appuyée sur Supabase, avec séries de régularité, XP et badges gamifiés pour garder la motivation.',
      feats: [
        'Génération de plans d’entraînement par IA à partir d’objectifs en langage naturel',
        'Suivi nutrition, macros et eau avec objectifs quotidiens',
        'Séries de régularité, XP et badges à débloquer',
        'Build Android natif via Capacitor',
      ],
      galleryCaps: [
        'Tableau de bord',
        'Entraînements · génération IA',
        'Repas et suivi de l’eau',
        'Calories et objectifs macros',
        'Onboarding profil santé',
      ],
    },
  },
  {
    id: 'echo',
    kind: 'Personal project',
    year: 'April 2026',
    live: null,
    name: 'Echo Art Studio',
    tagline: 'IBRAZIA — editorial luxury kimono storefront',
    cover: '/assets/echo/hero.webp',
    coverPos: 'center',
    desc: 'A high-end, editorial e-commerce concept for hand-woven kimono — built around a refined serif identity, “chapter”-based collections, and a slow, gallery-like browsing experience. Fully bilingual (EN/FR), with an adjustable product grid, filters, cart and product pages on a shadcn/ui component system.',
    feats: [
      'Editorial design system — serif display, restrained palette',
      'Collections presented as numbered “chapters” with cover art',
      'Bilingual EN/FR with i18next localization',
      'Adjustable grid views, filtering, cart & product pages',
    ],
    stack: ['React 18', 'TypeScript', 'Vite', 'Tailwind', 'shadcn/ui', 'i18next', 'Firebase'],
    shape: 'web',
    gallery: [
      { src: '/assets/echo/hero.webp', cap: 'Hero — every gesture' },
      { src: '/assets/echo/collections.webp', cap: 'Collections — eight chapters' },
      { src: '/assets/echo/grid1.webp', cap: 'All Kimono — product grid' },
      { src: '/assets/echo/grid2.webp', cap: 'Chapters 05–08' },
    ],
    fr: {
      kind: 'Projet personnel',
      tagline: 'IBRAZIA — boutique éditoriale de kimonos de luxe',
      desc: 'Un concept e-commerce éditorial haut de gamme pour kimonos tissés à la main — construit autour d’une identité serif raffinée, de collections organisées en « chapitres », et d’une navigation lente, façon galerie. Entièrement bilingue (EN/FR), avec grille produits ajustable, filtres, panier et fiches produit sur un système de composants shadcn/ui.',
      feats: [
        'Système graphique éditorial — police serif, palette sobre',
        'Collections présentées comme des « chapitres » numérotés avec visuel de couverture',
        'Bilingue EN/FR avec localisation i18next',
        'Grilles ajustables, filtres, panier et fiches produit',
      ],
      galleryCaps: [
        'Hero — chaque geste',
        'Collections — huit chapitres',
        'Tout le kimono — grille produits',
        'Chapitres 05–08',
      ],
    },
  },
  {
    id: 'eya',
    kind: 'Personal project',
    year: '2026',
    live: 'https://tanstack-start-app.eyatraining.workers.dev/',
    name: 'eya.',
    tagline: "Premium women's wellness & coaching platform",
    cover: '/assets/eya/home.webp',
    coverPos: 'top center',
    desc: 'A full-stack, bilingual coaching brand for women — blending personal coaching, nutrition and an online académie into one editorial, high-end experience. Built on TanStack Start with a Supabase backend and deployed to the edge on Cloudflare Workers.',
    feats: [
      'Bilingual FR/EN, editorial serif identity on olive & cream',
      'Interactive IMC (BMI) wellness tool',
      'Académie — premium online courses & programmes',
      'Nutrition, coaching, testimonials & contact',
    ],
    stack: ['TanStack Start', 'React 19', 'Tailwind v4', 'shadcn/ui', 'Supabase', 'Framer Motion', 'Cloudflare'],
    shape: 'web',
    gallery: [
      { src: '/assets/eya/home.webp', cap: 'Home — vous-même' },
      { src: '/assets/eya/imc.webp', cap: 'IMC — wellness tool' },
      { src: '/assets/eya/academie.webp', cap: 'Académie — online courses' },
      { src: '/assets/eya/nutrition.webp', cap: 'Nutrition & transformation' },
      { src: '/assets/eya/contact.webp', cap: 'Contact' },
    ],
    fr: {
      kind: 'Projet personnel',
      tagline: 'Plateforme premium de bien-être et coaching pour femmes',
      desc: 'Une marque de coaching bilingue full-stack pour femmes — mêlant coaching personnel, nutrition et une académie en ligne dans une expérience éditoriale haut de gamme. Construite sur TanStack Start avec un backend Supabase et déployée en edge sur Cloudflare Workers.',
      feats: [
        'Bilingue FR/EN, identité éditoriale serif sur olive & crème',
        'Outil bien-être IMC interactif',
        'Académie — cours et programmes en ligne premium',
        'Nutrition, coaching, témoignages & contact',
      ],
      galleryCaps: [
        'Accueil — vous-même',
        'IMC — outil bien-être',
        'Académie — cours en ligne',
        'Nutrition & transformation',
        'Contact',
      ],
    },
  },
  {
    id: 'visionnaire',
    kind: 'Personal project',
    year: '2026',
    live: 'https://ciseco-trial.web.app/',
    name: 'Visionnaire',
    tagline: 'Eyewear store with AR virtual try-on',
    cover: '/assets/visionnaire/home.webp',
    coverPos: 'top center',
    desc: 'A full eyewear e-commerce storefront built around a real designer catalogue — Dior, BOSS and more — where shoppers try frames on their own face in real time. The centrepiece is a FittingBox / FitMix AR integration: pick a frame, hit “Essayage virtuel”, and the glasses track to your face live in the browser. Backed by Firebase, with a privacy-first webcam flow and a custom analytics pipeline capturing user behaviour.',
    feats: [
      'Live AR try-on — FittingBox FitMix face-tracking in-browser',
      'Real designer catalogue with EAN, specs, colour & size data',
      'Cart, checkout, accounts & wishlist on a Redux Toolkit store',
      'Four switchable product-page variations via feature flag',
      'Custom tracking backend — Express + Gmail OAuth2, Excel export',
    ],
    stack: ['Next.js 14', 'TypeScript', 'Redux Toolkit', 'Tailwind', 'Firebase', 'FittingBox', 'Express'],
    shape: 'web',
    gallery: [
      { src: '/assets/visionnaire/home.webp', cap: 'Home — Style & Élégance' },
      { src: '/assets/visionnaire/collection.webp', cap: 'Collection — Dior & BOSS frames' },
      { src: '/assets/visionnaire/product.webp', cap: 'Product — full specs & virtual try-on' },
      { src: '/assets/visionnaire/tryon.webp', cap: 'AR try-on — FittingBox FitMix' },
    ],
    fr: {
      kind: 'Projet personnel',
      tagline: 'Boutique de lunetterie avec essayage virtuel AR',
      desc: 'Une boutique e-commerce de lunetterie complète construite autour d’un vrai catalogue de créateurs — Dior, BOSS et plus — où les clients essaient les montures sur leur propre visage en temps réel. Le cœur du projet est une intégration AR FittingBox / FitMix : on choisit une monture, on clique sur « Essayage virtuel », et les lunettes suivent le visage en direct dans le navigateur. Appuyée sur Firebase, avec un flux webcam respectueux de la vie privée et un pipeline analytique maison capturant le comportement utilisateur.',
      feats: [
        'Essayage AR en direct — suivi de visage FittingBox FitMix dans le navigateur',
        'Vrai catalogue de créateurs avec EAN, specs, couleur & données de taille',
        'Panier, paiement, comptes & liste de souhaits sur un store Redux Toolkit',
        'Quatre variantes de page produit interchangeables via feature flag',
        'Backend de suivi sur mesure — Express + Gmail OAuth2, export Excel',
      ],
      galleryCaps: [
        'Accueil — Style & Élégance',
        'Collection — montures Dior & BOSS',
        'Produit — specs complètes & essayage virtuel',
        'Essayage AR — FittingBox FitMix',
      ],
    },
  },
  {
    id: 'orizon',
    kind: 'Product · Full-Stack',
    year: '2025–26',
    live: 'https://orizon-booking-14409.web.app/',
    name: 'Orizon Event',
    tagline: 'Wedding & event services marketplace',
    cover: '/assets/orizon/home.webp',
    coverPos: 'top center',
    desc: 'A full marketplace for planning weddings and events end to end — couples browse venues, caterers, photographers, dresses and transport, then reserve and pay in one place, while providers run their own storefronts with subscriptions and a business dashboard. Built as three applications: a React client, an Angular 18 back-office and a NestJS API.',
    feats: [
      'Marketplace across 10+ service categories — venues to transport',
      'Provider portal — storefronts, subscription plans, payment history',
      'Bookings, cart & checkout with a token wallet and saved payment methods',
      'NestJS API — JWT roles, reviews, notifications, PDF invoicing',
      'Angular admin with NgRx, calendar scheduling & analytics dashboards',
    ],
    stack: ['React 18', 'TypeScript', 'Angular 18', 'NgRx', 'NestJS', 'MongoDB', 'Firebase', 'Docker'],
    shape: 'web',
    gallery: [
      { src: '/assets/orizon/home.webp', cap: 'Home — votre mariage de rêve' },
      { src: '/assets/orizon/venues.webp', cap: 'Lieux de réception — listings & ratings' },
      { src: '/assets/orizon/catering.webp', cap: 'Traiteur — curated caterers' },
      { src: '/assets/orizon/dresses.webp', cap: 'Catalogue de style — faceted filters' },
      { src: '/assets/orizon/shop.webp', cap: 'Boutique — token wallet & checkout' },
    ],
    fr: {
      kind: 'Produit · Full-Stack',
      tagline: 'Marketplace de services mariages & événements',
      desc: 'Une marketplace complète pour organiser mariages et événements de bout en bout — les couples parcourent lieux, traiteurs, photographes, robes et transport, puis réservent et paient au même endroit, pendant que les prestataires gèrent leur propre boutique avec abonnements et tableau de bord professionnel. Construite comme trois applications : un client React, un back-office Angular 18 et une API NestJS.',
      feats: [
        'Marketplace sur 10+ catégories de services — des lieux au transport',
        'Portail prestataire — boutiques, abonnements, historique de paiement',
        'Réservations, panier & paiement avec portefeuille de jetons et moyens de paiement enregistrés',
        'API NestJS — rôles JWT, avis, notifications, facturation PDF',
        'Admin Angular avec NgRx, planification calendrier & tableaux de bord analytiques',
      ],
      galleryCaps: [
        'Accueil — votre mariage de rêve',
        'Lieux de réception — listings & avis',
        'Traiteur — sélection de traiteurs',
        'Catalogue de style — filtres facettés',
        'Boutique — portefeuille de jetons & paiement',
      ],
    },
  },
  {
    id: 'ipacss',
    kind: 'Platform · Full-Stack',
    year: '2021–23',
    live: null,
    name: 'IPACSS',
    tagline: 'University campus-management platform',
    cover: null,
    desc: 'A large, multi-role platform for running a higher-education institution end to end — students, teachers, classes, subjects and study plans through to timetables, grades, attendance, internship offers, document requests and complaints. Built as a three-part system: a GraphQL API over MySQL, an Angular admin dashboard with super-admin / admin / staff roles, and an Ionic mobile companion for students and teachers. One of my largest projects, spanning ~60 data models.',
    feats: [
      'GraphQL API (Apollo + Sequelize + MySQL) — ~60 modelled entities',
      'Role-based Angular dashboard — super-admin, admin & staff',
      'Academic core — classes, modules, study plans, grades & attendance',
      'Careers — internship offers, CVs, applications & company links',
      'Ionic + Capacitor mobile app with JWT auth & barcode scanning',
      'JWT auth, file uploads & transactional email (Nodemailer / Mailjet)',
    ],
    stack: ['Angular 13', 'GraphQL', 'Apollo', 'Sequelize', 'MySQL', 'Node.js', 'Ionic', 'Capacitor'],
    shape: null,
    gallery: [],
    fr: {
      kind: 'Plateforme · Full-Stack',
      tagline: 'Plateforme de gestion de campus universitaire',
      desc: 'Une plateforme large et multi-rôles pour piloter un établissement d’enseignement supérieur de bout en bout — étudiants, enseignants, classes, matières et plans d’études jusqu’aux emplois du temps, notes, présences, offres de stage, demandes de documents et réclamations. Construite en trois parties : une API GraphQL sur MySQL, un tableau de bord admin Angular avec rôles super-admin / admin / staff, et une application mobile Ionic pour étudiants et enseignants. L’un de mes plus grands projets, avec près de 60 modèles de données.',
      feats: [
        'API GraphQL (Apollo + Sequelize + MySQL) — ~60 entités modélisées',
        'Tableau de bord Angular à rôles — super-admin, admin & staff',
        'Cœur académique — classes, modules, plans d’études, notes & présences',
        'Carrières — offres de stage, CV, candidatures & liens entreprises',
        'App mobile Ionic + Capacitor avec auth JWT & scan de codes-barres',
        'Auth JWT, envoi de fichiers & emails transactionnels (Nodemailer / Mailjet)',
      ],
    },
  },
  {
    id: 'cafe-caisse',
    kind: 'Product · Mobile',
    year: '2023',
    live: null,
    name: 'Café Caisse',
    tagline: 'Point-of-sale for cafés & restaurants',
    cover: null,
    desc: 'A tablet point-of-sale app for cafés and restaurants: open tables, take orders against a live product catalogue, and fire tickets to a thermal receipt printer. Built with Ionic and Angular, packaged for Android with Capacitor, and backed by Firebase — with a print queue that drives a Sunmi built-in printer through a Capacitor plugin.',
    feats: [
      'Table & order management with a live product catalogue',
      'Thermal receipt printing via the Sunmi inner-printer plugin',
      'Resilient print queue for unreliable hardware',
      'Firebase backend with offline-tolerant local storage',
      'Native Android build through Capacitor',
    ],
    stack: ['Ionic', 'Angular', 'Capacitor', 'Firebase', 'PrimeNG', 'Sunmi Printer'],
    shape: null,
    gallery: [],
    fr: {
      kind: 'Produit · Mobile',
      tagline: 'Caisse enregistreuse pour cafés & restaurants',
      desc: 'Une application caisse sur tablette pour cafés et restaurants : ouverture de tables, prise de commandes sur un catalogue produits en direct, et envoi des tickets vers une imprimante thermique. Construite avec Ionic et Angular, packagée pour Android avec Capacitor, et appuyée sur Firebase — avec une file d’impression qui pilote une imprimante intégrée Sunmi via un plugin Capacitor.',
      feats: [
        'Gestion des tables & commandes avec catalogue produits en direct',
        'Impression thermique via le plugin imprimante intégrée Sunmi',
        'File d’impression résiliente pour un matériel peu fiable',
        'Backend Firebase avec stockage local tolérant au hors-ligne',
        'Build Android natif via Capacitor',
      ],
    },
  },
  {
    id: 'esteps',
    kind: 'Professional · Contributor',
    year: '2023–24',
    live: null,
    name: 'Real-time healthcare SaaS',
    tagline: 'eSteps Health · Remote · Boston, MA-based startup',
    cover: null,
    desc: 'Real-time healthcare SaaS — contributed backend and full-stack development on a Node.js / Angular / AWS platform with real-time patient monitoring. Part of the engineering team behind the product that won first prize at Orange POESAM 2023.',
    feats: [
      'Real-time monitoring platform on Node.js, Angular & AWS',
      'Backend development & MongoDB performance work',
      'Part of the engineering team, delivery & reliability',
      '★ First Prize — Orange POESAM 2023',
    ],
    stack: ['Node.js', 'Angular', 'AWS', 'MongoDB'],
    shape: null,
    gallery: [],
    fr: {
      kind: 'Professionnel · Contributeur',
      tagline: 'eSteps Health · À distance · startup basée à Boston, MA',
      desc: 'SaaS santé en temps réel — contribution au développement backend et full-stack d’une plateforme Node.js / Angular / AWS avec suivi patient en temps réel. Membre de l’équipe d’ingénierie derrière le produit lauréat du premier prix Orange POESAM 2023.',
      feats: [
        'Plateforme de suivi en temps réel sur Node.js, Angular & AWS',
        'Développement backend & optimisation MongoDB',
        'Membre de l’équipe d’ingénierie, livraison & fiabilité',
        '★ Premier prix — Orange POESAM 2023',
      ],
    },
  },
  {
    id: 'aquadeep',
    kind: 'Professional · Technical Lead',
    year: '2024–25',
    live: null,
    name: 'Cloud platforms & reliability',
    tagline: 'Aquadeep',
    cover: null,
    desc: 'Technical leadership on AWS architectures, scalable services and CI/CD modernization — balancing speed of delivery with production stability and operational excellence.',
    feats: [
      'Scalable AWS architecture & services',
      'CI/CD modernization & faster, more reliable deploys',
      'Improved uptime via modern DevOps practices',
    ],
    stack: ['AWS', 'CI/CD', 'Leadership'],
    shape: null,
    gallery: [],
    fr: {
      kind: 'Professionnel · Lead technique',
      desc: 'Direction technique sur les architectures AWS, les services scalables et la modernisation CI/CD — en équilibrant vitesse de livraison, stabilité en production et excellence opérationnelle.',
      feats: [
        'Architecture & services AWS scalables',
        'Modernisation CI/CD & déploiements plus rapides et fiables',
        'Amélioration de la disponibilité via des pratiques DevOps modernes',
      ],
    },
  },
  {
    id: 'rms',
    kind: 'Professional · Full-Stack',
    year: '2026',
    live: null,
    name: 'Enterprise full-stack delivery',
    tagline: 'RMSoftware',
    cover: null,
    desc: 'Full-stack product work spanning Angular, NestJS, Flutter and Ionic with a strong emphasis on secure design patterns, microservices boundaries and pragmatic infrastructure choices. Acting as systems architect across deployment strategy.',
    feats: [
      'AWS architectures for production workloads',
      'Angular, NestJS, Flutter & Ionic delivery',
      'Security best practices — auth & data protection',
      'Microservices structure & deployment strategy',
    ],
    stack: ['Angular', 'NestJS', 'Flutter', 'Ionic'],
    shape: null,
    gallery: [],
    fr: {
      kind: 'Professionnel · Full-Stack',
      desc: 'Travail full-stack couvrant Angular, NestJS, Flutter et Ionic, avec un fort accent sur les patterns de sécurité, les frontières microservices et des choix d’infrastructure pragmatiques. Rôle d’architecte systèmes sur la stratégie de déploiement.',
      feats: [
        'Architectures AWS pour charges de production',
        'Livraison Angular, NestJS, Flutter & Ionic',
        'Bonnes pratiques de sécurité — auth & protection des données',
        'Structure microservices & stratégie de déploiement',
      ],
    },
  },
  {
    id: 'novavespera',
    kind: 'Personal · Brand',
    year: '2026',
    live: 'https://novavespera.pro/',
    name: 'Novavespera',
    tagline: 'Portfolio & brand presence',
    cover: null,
    desc: 'A focused showcase for engineering work, leadership and cloud-forward delivery — built for clarity, performance and credibility with prospective partners and hiring teams.',
    feats: ['Performance-first build', 'SEO & accessibility', 'Clear, credible brand presence'],
    stack: ['React', 'Performance', 'SEO'],
    shape: null,
    gallery: [],
    fr: {
      kind: 'Personnel · Marque',
      tagline: 'Portfolio & présence de marque',
      desc: 'Une vitrine ciblée pour le travail d’ingénierie, le leadership et la livraison cloud-first — pensée pour la clarté, la performance et la crédibilité auprès de partenaires et recruteurs potentiels.',
      feats: ['Build orienté performance', 'SEO & accessibilité', 'Présence de marque claire et crédible'],
    },
  },
];

/** Resolve a project list for the given locale, merging `fr` overrides onto the English base. */
export function localizeProjects(items: Project[], locale: string): Project[] {
  if (locale !== 'fr') return items;
  return items.map((p) => {
    const t = p.fr;
    if (!t) return p;
    return {
      ...p,
      kind: t.kind ?? p.kind,
      tagline: t.tagline ?? p.tagline,
      desc: t.desc ?? p.desc,
      feats: t.feats ?? p.feats,
      gallery: t.galleryCaps ? p.gallery.map((g, i) => ({ ...g, cap: t.galleryCaps![i] ?? g.cap })) : p.gallery,
    };
  });
}
