import type { Project } from './types';

/**
 * Project catalogue — the single source of truth for the Projects carousel
 * and case-study detail view. Imported by Carousel/CaseModal and used to
 * build JSON-LD structured data for SEO.
 */
export const projects: Project[] = [
  {
    id: 'fitcore',
    kind: 'Personal project',
    year: '2026',
    live: null,
    name: 'Fit-Core',
    tagline: 'Cross-platform fitness & nutrition companion',
    cover: '/assets/fitcore/home.webp',
    coverPos: 'top center',
    desc: 'A full fitness app designed and built end to end — guided health-profile onboarding with BMI & calorie targeting, AI-generated workout plans, and detailed nutrition tracking for calories, macros and water. Backed by Supabase with gamified streaks, XP and badges to keep training consistent.',
    feats: [
      'AI workout generation from natural-language goals',
      'Nutrition, macro & water tracking with daily targets',
      'Gamified streaks, XP and unlockable badges',
      'Native Android build via Capacitor',
    ],
    stack: ['Angular 20', 'Ionic', 'Capacitor', 'Supabase', 'TypeScript', 'Chart.js'],
    shape: 'phone',
    gallery: [
      { src: '/assets/fitcore/home.webp', cap: 'Home dashboard' },
      { src: '/assets/fitcore/workouts.webp', cap: 'Workouts · AI generation' },
      { src: '/assets/fitcore/nutrition.webp', cap: 'Meals & water tracking' },
      { src: '/assets/fitcore/calories.webp', cap: 'Calories & macro targets' },
      { src: '/assets/fitcore/onboarding.webp', cap: 'Health-profile onboarding' },
    ],
  },
  {
    id: 'echo',
    kind: 'Personal project',
    year: 'April 2026',
    live: null,
    name: 'Echo Art Studio',
    tagline: 'IBRAZIA — editorial luxury kimono storefront',
    cover: '/assets/echo/hero.webp',
    coverPos: 'center',
    desc: 'A high-end, editorial e-commerce concept for hand-woven kimono — built around a refined serif identity, “chapter”-based collections, and a slow, gallery-like browsing experience. Fully bilingual (EN/FR), with an adjustable product grid, filters, cart and product pages on a shadcn/ui component system.',
    feats: [
      'Editorial design system — serif display, restrained palette',
      'Collections presented as numbered “chapters” with cover art',
      'Bilingual EN/FR with i18next localization',
      'Adjustable grid views, filtering, cart & product pages',
    ],
    stack: ['React 18', 'TypeScript', 'Vite', 'Tailwind', 'shadcn/ui', 'i18next', 'Firebase'],
    shape: 'web',
    gallery: [
      { src: '/assets/echo/hero.webp', cap: 'Hero — every gesture' },
      { src: '/assets/echo/collections.webp', cap: 'Collections — eight chapters' },
      { src: '/assets/echo/grid1.webp', cap: 'All Kimono — product grid' },
      { src: '/assets/echo/grid2.webp', cap: 'Chapters 05–08' },
    ],
  },
  {
    id: 'eya',
    kind: 'Personal project',
    year: '2026',
    live: 'https://tanstack-start-app.eyatraining.workers.dev/',
    name: 'eya.',
    tagline: "Premium women's wellness & coaching platform",
    cover: '/assets/eya/home.webp',
    coverPos: 'top center',
    desc: 'A full-stack, bilingual coaching brand for women — blending personal coaching, nutrition and an online académie into one editorial, high-end experience. Built on TanStack Start with a Supabase backend and deployed to the edge on Cloudflare Workers.',
    feats: [
      'Bilingual FR/EN, editorial serif identity on olive & cream',
      'Interactive IMC (BMI) wellness tool',
      'Académie — premium online courses & programmes',
      'Nutrition, coaching, testimonials & contact',
    ],
    stack: ['TanStack Start', 'React 19', 'Tailwind v4', 'shadcn/ui', 'Supabase', 'Framer Motion', 'Cloudflare'],
    shape: 'web',
    gallery: [
      { src: '/assets/eya/home.webp', cap: 'Home — vous-même' },
      { src: '/assets/eya/imc.webp', cap: 'IMC — wellness tool' },
      { src: '/assets/eya/academie.webp', cap: 'Académie — online courses' },
      { src: '/assets/eya/nutrition.webp', cap: 'Nutrition & transformation' },
      { src: '/assets/eya/contact.webp', cap: 'Contact' },
    ],
  },
  {
    id: 'visionnaire',
    kind: 'Personal project',
    year: '2026',
    live: 'https://ciseco-trial.web.app/',
    name: 'Visionnaire',
    tagline: 'Eyewear store with AR virtual try-on',
    cover: '/assets/visionnaire/home.webp',
    coverPos: 'top center',
    desc: 'A full eyewear e-commerce storefront built around a real designer catalogue — Dior, BOSS and more — where shoppers try frames on their own face in real time. The centrepiece is a FittingBox / FitMix AR integration: pick a frame, hit “Essayage virtuel”, and the glasses track to your face live in the browser. Backed by Firebase, with a privacy-first webcam flow and a custom analytics pipeline capturing user behaviour.',
    feats: [
      'Live AR try-on — FittingBox FitMix face-tracking in-browser',
      'Real designer catalogue with EAN, specs, colour & size data',
      'Cart, checkout, accounts & wishlist on a Redux Toolkit store',
      'Four switchable product-page variations via feature flag',
      'Custom tracking backend — Express + Gmail OAuth2, Excel export',
    ],
    stack: ['Next.js 14', 'TypeScript', 'Redux Toolkit', 'Tailwind', 'Firebase', 'FittingBox', 'Express'],
    shape: 'web',
    gallery: [
      { src: '/assets/visionnaire/home.webp', cap: 'Home — Style & Élégance' },
      { src: '/assets/visionnaire/collection.webp', cap: 'Collection — Dior & BOSS frames' },
      { src: '/assets/visionnaire/product.webp', cap: 'Product — full specs & virtual try-on' },
      { src: '/assets/visionnaire/tryon.webp', cap: 'AR try-on — FittingBox FitMix' },
    ],
  },
  {
    id: 'orizon',
    kind: 'Product · Full-Stack',
    year: '2025–26',
    live: 'https://orizon-booking-14409.web.app/',
    name: 'Orizon Event',
    tagline: 'Wedding & event services marketplace',
    cover: '/assets/orizon/home.webp',
    coverPos: 'top center',
    desc: 'A full marketplace for planning weddings and events end to end — couples browse venues, caterers, photographers, dresses and transport, then reserve and pay in one place, while providers run their own storefronts with subscriptions and a business dashboard. Built as three applications: a React client, an Angular 18 back-office and a NestJS API.',
    feats: [
      'Marketplace across 10+ service categories — venues to transport',
      'Provider portal — storefronts, subscription plans, payment history',
      'Bookings, cart & checkout with a token wallet and saved payment methods',
      'NestJS API — JWT roles, reviews, notifications, PDF invoicing',
      'Angular admin with NgRx, calendar scheduling & analytics dashboards',
    ],
    stack: ['React 18', 'TypeScript', 'Angular 18', 'NgRx', 'NestJS', 'MongoDB', 'Firebase', 'Docker'],
    shape: 'web',
    gallery: [
      { src: '/assets/orizon/home.webp', cap: 'Home — votre mariage de rêve' },
      { src: '/assets/orizon/venues.webp', cap: 'Lieux de réception — listings & ratings' },
      { src: '/assets/orizon/catering.webp', cap: 'Traiteur — curated caterers' },
      { src: '/assets/orizon/dresses.webp', cap: 'Catalogue de style — faceted filters' },
      { src: '/assets/orizon/shop.webp', cap: 'Boutique — token wallet & checkout' },
    ],
  },
  {
    id: 'ipacss',
    kind: 'Platform · Full-Stack',
    year: '2021–23',
    live: null,
    name: 'IPACSS',
    tagline: 'University campus-management platform',
    cover: null,
    desc: 'A large, multi-role platform for running a higher-education institution end to end — students, teachers, classes, subjects and study plans through to timetables, grades, attendance, internship offers, document requests and complaints. Built as a three-part system: a GraphQL API over MySQL, an Angular admin dashboard with super-admin / admin / staff roles, and an Ionic mobile companion for students and teachers. One of my largest projects, spanning ~60 data models.',
    feats: [
      'GraphQL API (Apollo + Sequelize + MySQL) — ~60 modelled entities',
      'Role-based Angular dashboard — super-admin, admin & staff',
      'Academic core — classes, modules, study plans, grades & attendance',
      'Careers — internship offers, CVs, applications & company links',
      'Ionic + Capacitor mobile app with JWT auth & barcode scanning',
      'JWT auth, file uploads & transactional email (Nodemailer / Mailjet)',
    ],
    stack: ['Angular 13', 'GraphQL', 'Apollo', 'Sequelize', 'MySQL', 'Node.js', 'Ionic', 'Capacitor'],
    shape: null,
    gallery: [],
  },
  {
    id: 'cafe-caisse',
    kind: 'Product · Mobile',
    year: '2023',
    live: null,
    name: 'Café Caisse',
    tagline: 'Point-of-sale for cafés & restaurants',
    cover: null,
    desc: 'A tablet point-of-sale app for cafés and restaurants: open tables, take orders against a live product catalogue, and fire tickets to a thermal receipt printer. Built with Ionic and Angular, packaged for Android with Capacitor, and backed by Firebase — with a print queue that drives a Sunmi built-in printer through a Capacitor plugin.',
    feats: [
      'Table & order management with a live product catalogue',
      'Thermal receipt printing via the Sunmi inner-printer plugin',
      'Resilient print queue for unreliable hardware',
      'Firebase backend with offline-tolerant local storage',
      'Native Android build through Capacitor',
    ],
    stack: ['Ionic', 'Angular', 'Capacitor', 'Firebase', 'PrimeNG', 'Sunmi Printer'],
    shape: null,
    gallery: [],
  },
  {
    id: 'esteps',
    kind: 'Professional · Lead',
    year: '2023–24',
    live: null,
    name: 'Real-time healthcare SaaS',
    tagline: 'eSteps Health',
    cover: null,
    desc: 'End-to-end platform engineering for a real-time healthcare product: Node.js and Angular on AWS, MongoDB performance work, and team leadership across delivery, reliability and latency-sensitive features. Led a team of 10, improved data retrieval by 20% and reduced latency by 15%.',
    feats: [
      'Real-time monitoring platform on Node.js, Angular & AWS',
      'MongoDB optimization — 20% faster data retrieval',
      'Led 10 engineers, +25% team productivity',
      '★ First Prize — POESAM 2023',
    ],
    stack: ['Node.js', 'Angular', 'AWS', 'MongoDB'],
    shape: null,
    gallery: [],
  },
  {
    id: 'aquadeep',
    kind: 'Professional · Technical Lead',
    year: '2024–25',
    live: null,
    name: 'Cloud platforms & reliability',
    tagline: 'Aquadeep',
    cover: null,
    desc: 'Technical leadership on AWS architectures, scalable services and CI/CD modernization — balancing speed of delivery with production stability and operational excellence. Established pipelines that cut deployment times by 30%.',
    feats: [
      'Scalable AWS architecture & services',
      'CI/CD modernization — 30% faster deploys',
      'Improved uptime via modern DevOps practices',
    ],
    stack: ['AWS', 'CI/CD', 'Leadership'],
    shape: null,
    gallery: [],
  },
  {
    id: 'rms',
    kind: 'Professional · Full-Stack',
    year: '2026',
    live: null,
    name: 'Enterprise full-stack delivery',
    tagline: 'RMSoftware',
    cover: null,
    desc: 'Full-stack product work spanning Angular, NestJS, Flutter and Ionic with a strong emphasis on secure design patterns, microservices boundaries and pragmatic infrastructure choices. Acting as systems architect across deployment strategy.',
    feats: [
      'AWS architectures for production workloads',
      'Angular, NestJS, Flutter & Ionic delivery',
      'Security best practices — auth & data protection',
      'Microservices structure & deployment strategy',
    ],
    stack: ['Angular', 'NestJS', 'Flutter', 'Ionic'],
    shape: null,
    gallery: [],
  },
  {
    id: 'novavespera',
    kind: 'Personal · Brand',
    year: '2026',
    live: 'https://novavespera.pro/',
    name: 'Novavespera',
    tagline: 'Portfolio & brand presence',
    cover: null,
    desc: 'A focused showcase for engineering work, leadership and cloud-forward delivery — built for clarity, performance and credibility with prospective partners and hiring teams.',
    feats: ['Performance-first build', 'SEO & accessibility', 'Clear, credible brand presence'],
    stack: ['React', 'Performance', 'SEO'],
    shape: null,
    gallery: [],
  },
];
