import type { Project } from './types';

/**
 * Project catalogue — the single source of truth for the Projects carousel
 * and case-study detail view. Imported by Carousel/CaseModal and used to
 * build JSON-LD structured data for SEO.
 */
export const projects: Project[] = [
  {
    id: 'fitcore',
    kind: 'Personal project',
    year: '2026',
    live: null,
    name: 'Fit-Core',
    tagline: 'Cross-platform fitness & nutrition companion',
    cover: '/assets/fitcore/home.webp',
    coverPos: 'top center',
    desc: 'A full fitness app designed and built end to end — guided health-profile onboarding with BMI & calorie targeting, AI-generated workout plans, and detailed nutrition tracking for calories, macros and water. Backed by Supabase with gamified streaks, XP and badges to keep training consistent.',
    feats: [
      'AI workout generation from natural-language goals',
      'Nutrition, macro & water tracking with daily targets',
      'Gamified streaks, XP and unlockable badges',
      'Native Android build via Capacitor',
    ],
    stack: ['Angular 20', 'Ionic', 'Capacitor', 'Supabase', 'TypeScript', 'Chart.js'],
    shape: 'phone',
    gallery: [
      { src: '/assets/fitcore/home.webp', cap: 'Home dashboard' },
      { src: '/assets/fitcore/workouts.webp', cap: 'Workouts · AI generation' },
      { src: '/assets/fitcore/nutrition.webp', cap: 'Meals & water tracking' },
      { src: '/assets/fitcore/calories.webp', cap: 'Calories & macro targets' },
      { src: '/assets/fitcore/onboarding.webp', cap: 'Health-profile onboarding' },
    ],
  },
  {
    id: 'echo',
    kind: 'Personal project',
    year: 'April 2026',
    live: null,
    name: 'Echo Art Studio',
    tagline: 'IBRAZIA — editorial luxury kimono storefront',
    cover: '/assets/echo/hero.webp',
    coverPos: 'center',
    desc: 'A high-end, editorial e-commerce concept for hand-woven kimono — built around a refined serif identity, “chapter”-based collections, and a slow, gallery-like browsing experience. Fully bilingual (EN/FR), with an adjustable product grid, filters, cart and product pages on a shadcn/ui component system.',
    feats: [
      'Editorial design system — serif display, restrained palette',
      'Collections presented as numbered “chapters” with cover art',
      'Bilingual EN/FR with i18next localization',
      'Adjustable grid views, filtering, cart & product pages',
    ],
    stack: ['React 18', 'TypeScript', 'Vite', 'Tailwind', 'shadcn/ui', 'i18next', 'Firebase'],
    shape: 'web',
    gallery: [
      { src: '/assets/echo/hero.webp', cap: 'Hero — every gesture' },
      { src: '/assets/echo/collections.webp', cap: 'Collections — eight chapters' },
      { src: '/assets/echo/grid1.webp', cap: 'All Kimono — product grid' },
      { src: '/assets/echo/grid2.webp', cap: 'Chapters 05–08' },
    ],
  },
  {
    id: 'eya',
    kind: 'Personal project',
    year: '2026',
    live: 'https://tanstack-start-app.eyatraining.workers.dev/',
    name: 'eya.',
    tagline: "Premium women's wellness & coaching platform",
    cover: '/assets/eya/home.webp',
    coverPos: 'top center',
    desc: 'A full-stack, bilingual coaching brand for women — blending personal coaching, nutrition and an online académie into one editorial, high-end experience. Built on TanStack Start with a Supabase backend and deployed to the edge on Cloudflare Workers.',
    feats: [
      'Bilingual FR/EN, editorial serif identity on olive & cream',
      'Interactive IMC (BMI) wellness tool',
      'Académie — premium online courses & programmes',
      'Nutrition, coaching, testimonials & contact',
    ],
    stack: ['TanStack Start', 'React 19', 'Tailwind v4', 'shadcn/ui', 'Supabase', 'Framer Motion', 'Cloudflare'],
    shape: 'web',
    gallery: [
      { src: '/assets/eya/home.webp', cap: 'Home — vous-même' },
      { src: '/assets/eya/imc.webp', cap: 'IMC — wellness tool' },
      { src: '/assets/eya/academie.webp', cap: 'Académie — online courses' },
      { src: '/assets/eya/nutrition.webp', cap: 'Nutrition & transformation' },
      { src: '/assets/eya/contact.webp', cap: 'Contact' },
    ],
  },
  {
    id: 'esteps',
    kind: 'Professional · Lead',
    year: '2023–24',
    live: null,
    name: 'Real-time healthcare SaaS',
    tagline: 'eSteps Health',
    cover: null,
    desc: 'End-to-end platform engineering for a real-time healthcare product: Node.js and Angular on AWS, MongoDB performance work, and team leadership across delivery, reliability and latency-sensitive features. Led a team of 10, improved data retrieval by 20% and reduced latency by 15%.',
    feats: [
      'Real-time monitoring platform on Node.js, Angular & AWS',
      'MongoDB optimization — 20% faster data retrieval',
      'Led 10 engineers, +25% team productivity',
      '★ First Prize — POESAM 2023',
    ],
    stack: ['Node.js', 'Angular', 'AWS', 'MongoDB'],
    shape: null,
    gallery: [],
  },
  {
    id: 'aquadeep',
    kind: 'Professional · Technical Lead',
    year: '2024–25',
    live: null,
    name: 'Cloud platforms & reliability',
    tagline: 'Aquadeep',
    cover: null,
    desc: 'Technical leadership on AWS architectures, scalable services and CI/CD modernization — balancing speed of delivery with production stability and operational excellence. Established pipelines that cut deployment times by 30%.',
    feats: [
      'Scalable AWS architecture & services',
      'CI/CD modernization — 30% faster deploys',
      'Improved uptime via modern DevOps practices',
    ],
    stack: ['AWS', 'CI/CD', 'Leadership'],
    shape: null,
    gallery: [],
  },
  {
    id: 'rms',
    kind: 'Professional · Full-Stack',
    year: '2026',
    live: null,
    name: 'Enterprise full-stack delivery',
    tagline: 'RMSoftware',
    cover: null,
    desc: 'Full-stack product work spanning Angular, NestJS, Flutter and Ionic with a strong emphasis on secure design patterns, microservices boundaries and pragmatic infrastructure choices. Acting as systems architect across deployment strategy.',
    feats: [
      'AWS architectures for production workloads',
      'Angular, NestJS, Flutter & Ionic delivery',
      'Security best practices — auth & data protection',
      'Microservices structure & deployment strategy',
    ],
    stack: ['Angular', 'NestJS', 'Flutter', 'Ionic'],
    shape: null,
    gallery: [],
  },
  {
    id: 'novavespera',
    kind: 'Personal · Brand',
    year: '2026',
    live: 'https://novavespera.pro/',
    name: 'Novavespera',
    tagline: 'Portfolio & brand presence',
    cover: null,
    desc: 'A focused showcase for engineering work, leadership and cloud-forward delivery — built for clarity, performance and credibility with prospective partners and hiring teams.',
    feats: ['Performance-first build', 'SEO & accessibility', 'Clear, credible brand presence'],
    stack: ['React', 'Performance', 'SEO'],
    shape: null,
    gallery: [],
  },
];
